export const CUSTOM_UTIL_BUILDER_REPLACED = "CUSTOM_UTIL_BUILDER_REPLACED";
export const CUSTOM_ATOM_BUILDER_REPLACED = "CUSTOM_ATOM_BUILDER_REPLACED";
export const CUSTOM_COMPONENT_BUILDER_REPLACED =
	"CUSTOM_COMPONENT_BUILDER_REPLACED";
